sonar.organization=yo1115   # 你的 SonarCloud org key
sonar.projectKey=Yo1115_paris_sonar  # SonarCloud 上顯示的 project key

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/vendor/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
